config/routes.rb
Rails.application.routes.draw do
  
  
 
 

  get 'pages/index'

  devise_for :users
  resources :types
  resources :statuses
  resources :subcategory2s
    resources :subcategory1s

  resources :items do
    collection do
      get 'search'
    end
    collection do
      get 'searc'
    end
  end
  
  resources :categories 
    
  
    get 'pages/realestate'
    get 'pages/sea', to: "pages#sea"
   
 
 match '/sub1_categories/find_by_category', to: 'sub1_categories#find_by_category', via: :post
 
 
  root 'welcome#index'
 
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
     belongs_to :category
     belongs_to :statuses
     belongs_to :types

     def self.search(params)
       items = Item.where(params[:listing])
       items = items.where(" name like ? ","%#{params[:search]}%") if params[:search].present?
     end

     def searc
     end


end

app/models/realestate.rb
class Realestate < ActiveRecord::Base
end

app/models/sea.rb
class Sea < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
    has_many :items
end

app/models/sub1_category.rb
class Sub1Category < ActiveRecord::Base
     belongs_to :category
end

app/models/sub2_category.rb
class Sub2Category < ActiveRecord::Base
     belongs_to :category
end

app/models/suba_category.rb
class SubaCategory < ActiveRecord::Base
    belongs_to :category
end

app/models/subcategory1.rb
class Subcategory1 < ActiveRecord::Base
    belongs_to :category
end

app/models/subcategory2.rb
class Subcategory2 < ActiveRecord::Base
     belongs_to :category
end

app/models/type.rb
class Type < ActiveRecord::Base
    has_many :items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    @cottage = @categories[0]
    @apartment = @categories[1]
    @townhouse = @categories[2]
    @items = Item.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @items = Item.where(category_id: params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :searc]


  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  def searc
  redirect_to items_path  
  end
  

  def search
    @items = Item.search(params)
    if @items.blank?
      flash[:notice] = "nothing found"
    end
  end
  
  
  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :sqft, :rooms, :built_year, :cost, :address, :category_id, :status_id, :type_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:listing_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<br>
<br>

    

<p id="notice"><%= notice %></p>

<div class="container">
    
   <% if @items.present? %>
    <% @items.each do |item| %>
    <p>

  <%= item.address %>
</p>

<iframe
  width="1150"
  height="300"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=
  AIzaSyCDUjG6U31VxADJBuliYaemivyDZYUK2Xw
    &q=Space+Needle,Seattle+WA" allowfullscreen>
</iframe>

<br>
<br>

<div id="ShowOrderBy">
        <form method="POST"  name="orderForm">
            <input type="hidden" id="order_direction" name="order_direction" value="asc">
              <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true">  </span>         
                Order By <select>
                            <option value="date">  Date </option>
                            <option value="price"> Price</option>
                            <option value="htitle" selected="selected"> Title</option>
                        </select>
        </form>
</div>



 <div class="row">
        <div class="col-md-3">
        <div class="thumbnail">
         
            <div class="caption">
            <b>  <%= item.name %>  </b> <br>
               <span class="glyphicon glyphicon-resize-full" aria-hidden="true"> <%= item.sqft %> </b></span> &nbsp; &nbsp; &nbsp; &nbsp;
                &nbsp; &nbsp;    &nbsp; &nbsp;  <span class=" glyphicon glyphicon-home"> <%= item.rooms %> </span>   <br> <br>
                
                 <span class="glyphicon glyphicon-calendar" aria-hidden="true"> 
                  
                   </span> Built Year : <br>
                  
                   <%= item.built_year %> 
                   <br> <br>
                  <button class: logbutton>
                    <%= item.cost %> USD 
                 
             
                <%= link_to 'View Listing', item, class: "btn btn-link" %></td>
              
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                
            </div>
          </div>
        </div>
    <% end %>
     <% else %>
     <p> no items found </p>
     <% end %>
    
    </div>
  </div>
 </button>
<%= link_to 'New Listing', new_item_path %>